### ISSUE TITLE
Consider contributing to zsh-completions

### ISSUE THREAD

**Issue by tt** [felixr/docker-zsh-completion#17]
I hope you'll consider contributing to [zsh-users/zsh-completions](zsh-users/zsh-completions). All those completions can be installed with `brew install zsh-completions`, so you can reach all the users who didn't explicitly search for this project.

**Comment by vincentbernat** [comment]
Not much to do here. There is a copy of this repository in Docker. There is a little interest to have another copy in zsh-completions.
