### ISSUE TITLE
Bug with zsh 5.0.7

### ISSUE THREAD

**Issue by mhoeschele** [felixr/docker-zsh-completion#25]
The completion does not work (only shows the help command) with the current zsh version that changed some behavior. You need to change line 181 from

lines=(${(f)"$(_call_program commands docker 2>&1)"})

to

lines=(${(f)"$(_call_program commands "docker 2>&1")"})

in order to fix this issue.

**Comment by reduardo7** [comment]
Fix: https://github.com/felixr/docker-zsh-completion

**Comment by vincentbernat** [comment]
zsh 5.0.8 was released in May 2015. Let's close this bug.
