### ISSUE TITLE
Images with colon in name don't complete correctly

### ISSUE THREAD

**Issue by EclipseTech** [felixr/docker-zsh-completion#26]
For images pushing to a private repository, such as on port 5000 this causes completion issues.
Steps to reproduce:
```docker pull ubuntu```
```docker tag ubuntu my-repo:5000/ubuntu```
```docker rmi my-<TAB>```

Expected:
```docker rmi my-repo:5000/ubuntu```

Actual:
```docker rmi my-repo ```

**Comment by vincentbernat** [comment]
How is that different from image `my-repo`, tag `5000/ubuntu`? Is `/` forbidden in tags?

**Comment by EclipseTech** [comment]
/ is not forbidden in tags. my-repo:5000/ubuntu is a valid tag
$ docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
my-repo:5000/ubuntu                    latest              d2a0ecffe6fa        5 days ago          188.4 MB
ubuntu                                           latest              d2a0ecffe6fa        5 days ago          188.4 MB

**Comment by vincentbernat** [comment]
Suppose you have this:

```
$ docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
my-repo:5000/ubuntu                    latest              d2a0ecffe6fa        5 days ago          188.4 MB
my-repo                                5000/ubuntu         aaaaaaaaaaaa        5 days ago          188.4 MB
```

Both images will be `my-repo:5000/ubuntu`. How does Docker tell them apart? I don't see a way to have `/` in the tag part, so I suppose this could be the way to differenciate them.

**Comment by EclipseTech** [comment]
I was wrong, / is not valid in tags, you couldn't get Image:my-repo  tag:5000/ubuntu the colon is valid before /, it seems the first colon can either denote part of the image name if followed by a / or tag, the second colon is only okay if the first colon meant the port, otherwise you get:
FATA[0000] Invalid namespace name (works:something). Only [a-z0-9-_] are allowed.

**Comment by vincentbernat** [comment]
Could you try commit 1c504eb? And reopen if it doesn't work as expected.

**Comment by sargon2** [comment]
1c504eb works for me (I had the same issue).  Thanks for the quick fix.
