### ISSUE TITLE
Install instructions for use with Prezto

### ISSUE THREAD

**Issue by Glutnix** [felixr/docker-zsh-completion#28]
`curl -fLo $HOME/.zprezto/modules/completion/external/src/_docker   https://raw.githubusercontent.com/docker/docker/master/contrib/completion/zsh/_docker`

Could this be included in the installation instructions?

**Comment by vincentbernat** [comment]
Yes, it could. Could you do a PR?

**Comment by Glutnix** [comment]
On it.
