### ISSUE TITLE
Add new installation method

### ISSUE THREAD

**Issue by b4b4r07** [felixr/docker-zsh-completion#30]
Hi,

This is amazing completion file! I appreciate it.
BTW, by using [zplug](https://github.com/b4b4r07/zplug), we can easily install docker-zsh-completion.

Would you add this installation method to your README?

```console
$ zplug "felixr/docker-zsh-completion"
```

**Comment by vincentbernat** [comment]
Just added a line about it.

**Comment by b4b4r07** [comment]
Cool! Thank you very much.
