### ISSUE TITLE
auto complete with options failed with short combination

### ISSUE THREAD

**Issue by franciscocpg** [felixr/docker-zsh-completion#32]
I am trying to run a docker exec on a running container.
If I use `docker exec -i -t` and hit tab, completion is working fine, but If use the short `docker exec -it` does not work (running containers are not listed).
Using docker bash completion, both options works.

**Comment by vincentbernat** [comment]
Are you using the version from this repository or the version shipped with Docker? There is a slight difference between the two versions in relation to your use case. See the comments at the very top of the completion file:

```
# Short-option stacking can be disabled with:
#  zstyle ':completion:*:*:docker:*' option-stacking no
#  zstyle ':completion:*:*:docker-*:*' option-stacking no
__docker_arguments() {
    if zstyle -T ":completion:${curcontext}:" option-stacking; then
        print -- -s
    fi
}
```

**Comment by franciscocpg** [comment]
Hi @vincentbernat 
I am using oh my zsh and I done this:
```
mkdir -p ~/.oh-my-zsh/plugins/docker/
curl -fLo ~/.oh-my-zsh/plugins/docker/_docker https://raw.github.com/felixr/docker-zsh-completion/master/_docker
```
So I think I am using the version from this repository.

**Comment by vincentbernat** [comment]
If you remove the file and `exec zsh`, the completion doesn't work anymore, right?

Which version of zsh are you using?

**Comment by franciscocpg** [comment]
I removed `~/.oh-my-zsh/plugins/docker/_docker`, execute `exec zsh` and is still working completion.
```
zsh --version
zsh 5.0.2 (x86_64-pc-linux-gnu)
```

**Comment by vincentbernat** [comment]
OK, this means that you have the completion from docker somewhere else. You don't need to download it separately then. You only need to enable option stacking. Use the following commands:

```
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
```

**Comment by franciscocpg** [comment]
It worked!
I have a docker completion here
`/etc/bash_completion.d/docker`
So zsh is reading from there?

**Comment by vincentbernat** [comment]
Unless you have something specific, zsh is not able to use bash completions. And if it does, it won't respect zstyle. Maybe it comes directly with Docker packages. This can be in `/usr/share/zsh` too.

**Comment by franciscocpg** [comment]
Yes, you are right.
`/usr/share/zsh/vendor-completions/_docker`
Thank you
