### ISSUE TITLE
Deprecation of this repository?

### ISSUE THREAD

**Issue by vincentbernat** [felixr/docker-zsh-completion#35]
Hey!

Until recently, I was keeping up-to-date this repository by syncing changes from Docker. The only differences between this repository and the completion proposed by Docker are:

 1. Lateness
 2. Stacking option (documented at the top of the file)
 3. Integration with different frameworks.

I don't think it's worth continuing maintaining this repository. I didn't check, but maybe people installing Docker automatically gets the ZSH completion along with Docker itself. If not, that's maybe something to suggest instead of relying on a third-party repository. Moreover, this enables to have the completion matches your Docker version.

cc @sdurrheimer @ninrod

**Comment by ninrod** [comment]
@vincentbernat no problem at all. I think I'll just grab the completion directly from docker then. Thanks for working in this up to this point.

**Comment by sdurrheimer** [comment]
I'm encountering the same issue with [sdurrheimer/docker-compose-zsh-completion](https://github.com/sdurrheimer/docker-compose-zsh-completion), it is quite hard and time consuming to maintain the zsh-completion in both dockers and side repositories (to the extent that mine is out of sync.).

So I totally agree with you and I will certainly to the same with my repo.
