### ISSUE TITLE
docker exec autocomplete

### ISSUE THREAD

**Issue by TintypeMolly** [felixr/docker-zsh-completion#41]
Hi. Thanks for your contribution. I enjoy using this zsh plugin thru oh-my-zsh.

I use exec a lot to attach to a running container.  
My use case looks like `docker exec -it container_name /bin/bash`

I once thought that autocomp for exec container names might be just missing, but I figured that your plugin does support autocomplete for the exec target container name, if I don't give `-it` option at all, or if given `-i -t` separately.

It would be nice if it works when `-it` option is given to `exec` command

### Current Behavior

1. `docker exec -it con` and hit tab, then doesn't autocomplete. :x:
2. `docker exec con` and hit tab, then autocomplete works. :o:
3. `docker exec -i -t con` and hit tab, then autocomplete works. :o:

### Suggestion
It would be nice if autocomp works on case 1.

**Comment by vincentbernat** [comment]
This repository is deprecated. I think you are using the completion directly from docker. Look at the top of the README to make option stacking work as you expect.

**Comment by TintypeMolly** [comment]
@vincentbernat oops thx. I'll bring this to them.
